import { launch } from "./harness.mjs";
const out = process.argv[2] ?? "/tmp";
const w = Number(process.argv[3] ?? 1280), h = Number(process.argv[4] ?? 800);
const browser = await launch();
const context = await browser.newContext({ viewport: { width: w, height: h } });
const page = await context.newPage();
const logs = [];
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") logs.push(m.type() + " " + m.text().slice(0, 200)); });
page.on("pageerror", (e) => logs.push("pageerror " + String(e).slice(0, 300)));
await page.goto("http://localhost:4311/", { timeout: 20000 });
await page.waitForFunction(() => !!window.bankIt, null, { timeout: 30000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/title.png` });
await page.click("text=Freestyle");
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/pick.png` });
await page.click("[data-id=bin-there]");
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/play.png` });
console.log(JSON.stringify(await page.evaluate(() => { const s = window.bankIt.state(); return { phase: s.phase, overlay: s.overlay, px: s.pxPerMetre, insets: s.insets }; })));
console.log(logs.slice(0, 10).join("\n"));
await browser.close();
