import { BASE, launch } from "./harness.mjs";
const out = process.argv[2] ?? "/tmp";
const [w, h] = (process.argv[3] ?? "1280x800").split("x").map(Number);
const browser = await launch();
const page = await (await browser.newContext({ viewport: { width: w, height: h } })).newPage();
await page.goto(BASE);
await page.waitForFunction(() => !!window.bankIt, null, { timeout: 30000 });
await page.waitForTimeout(700);
await page.screenshot({ path: `${out}/m-title-${w}.png` });
await page.click("text=Called Shots");
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/m-challenges-${w}.png` });
await page.click("[data-action=back]");
await page.waitForTimeout(300);
await page.click("text=How to play");
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/m-help-${w}.png` });
await page.click("[data-action=back]");
await page.waitForTimeout(300);
await page.click("text=Freestyle");
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/m-freestyle-${w}.png` });
await page.click("[data-id=bin-there]");
await page.waitForTimeout(400);
await page.keyboard.press("Escape");
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/m-pause-${w}.png` });
await browser.close();
