// Replays every Called Shot's recorded solution through the real simulation
// and prints a Markdown report: launch position, angle, power, release tick,
// the route it takes, its score, and how forgiving the aim is (how many of the
// neighbouring aims, one keyboard step away, also make the challenge).
//
//   node scripts/solutions.ts            # print the report
//   node scripts/solutions.ts --write    # also write SOLUTIONS.md
import { writeFileSync } from "node:fs";
import { CHALLENGES } from "../src/levels/challenges.ts";
import { layoutById } from "../src/levels/layouts.ts";
import { challengeComplete, describeRequirement } from "../src/rules/challenges.ts";
import { scoreChain } from "../src/rules/scoring.ts";
import { logEvent, newShotLog } from "../src/rules/shotLog.ts";
import { formatAngle, formatPower } from "../src/sim/launch.ts";
import { loadRapier } from "../src/sim/rapier.ts";
import { runShot } from "../src/sim/shot.ts";
import type { Aim } from "../src/sim/types.ts";

const R = await loadRapier();
const rows: string[] = [];
let failures = 0;

function attempt(layoutId: string, aim: Aim, releaseTick: number) {
  const layout = layoutById(layoutId);
  const res = runShot(R, { layout, aim, releaseTick });
  const log = newShotLog();
  for (const e of res.events) logEvent(log, e);
  return { res, log, layout };
}

for (const c of CHALLENGES) {
  const { log, layout } = attempt(c.layoutId, c.solution.aim, c.solution.releaseTick);
  const ok = challengeComplete(c.requirement, log);
  if (!ok) failures++;
  // Forgiveness: neighbours one fine step (0.1° / 0.1%) and one normal step (0.5° / 0.5%) away.
  const around = (step: number) => {
    let n = 0;
    for (const [da, dp] of [
      [step, 0],
      [-step, 0],
      [0, step],
      [0, -step],
    ]) {
      const aim = { angleTenths: c.solution.aim.angleTenths + da, powerTenths: c.solution.aim.powerTenths + dp };
      if (challengeComplete(c.requirement, attempt(c.layoutId, aim, c.solution.releaseTick).log)) n++;
    }
    return n;
  };
  let timing = "";
  if (layout.props.some((p) => p.type === "bird")) {
    let n = 0;
    for (const dt of [-2, -1, 1, 2]) if (challengeComplete(c.requirement, attempt(c.layoutId, c.solution.aim, c.solution.releaseTick + dt).log)) n++;
    timing = `${n}/4`;
  }
  const label = (id: string) => layout.props.find((p) => p.id === id)?.label ?? id;
  rows.push(
    `| ${c.number} | ${c.title} | ${describeRequirement(c.requirement, label)} | ${layout.name} | (${c.solution.launch.x}, ${c.solution.launch.y}) | ${formatAngle(c.solution.aim)} | ${formatPower(c.solution.aim)} | ${c.solution.releaseTick} | ${log.sequence.map((s) => label(s).toUpperCase()).join(" → ") || "—"} | ${scoreChain(log).total} | ${around(1)}/4 · ${around(5)}/4${timing ? ` · t ${timing}` : ""} | ${ok ? "✓" : "✗ FAILS"} |`,
  );
}

const md = `# Called Shot solutions

Generated by \`node scripts/solutions.ts --write\` from \`src/levels/challenges.ts\`.
Every row is replayed through the real simulation by \`tests/solutions.test.ts\`.

- **Launch** is where the ball sits before the shot (metres, from the kerb and the driveway).
- **Angle** is measured anticlockwise from pointing right; **power** maps to launch speed.
- **Release tick** is the number of 1/120 s ticks after the attempt starts (the ball
  appears in the kid's hands and the seagull restarts its loop) before letting go.
  Only the seagull layout depends on it.
- **Forgiveness** counts the neighbouring aims that also make the challenge: one
  fine keyboard step away (0.1° or 0.1%), then one normal step away (0.5° or 0.5%),
  then (for the seagull) releases one or two ticks early or late.

| # | Challenge | Route to make | Layout | Launch | Angle | Power | Release tick | Actual route | Score | Forgiveness | Check |
|---|---|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}
`;
console.log(md);
if (process.argv.includes("--write")) writeFileSync(new URL("../SOLUTIONS.md", import.meta.url), md);
if (failures) {
  console.error(`${failures} challenge solution(s) fail`);
  process.exit(1);
}
